@startuml

title __DETECTIVEHANGMAN's Class Diagram__\n

  namespace DetectiveHangman {
    class DetectiveHangman.Detective {
        - correctLettersGuessed : ArrayList<Character>
        - guessedLocation : String
        - guessedMotive : String
        - guessedMurderer : String
        - guessedVictim : String
        - guessedWeapon : String
        - playerGuesses : ArrayList<Character>
        + Detective()
        + displayLettersGuessed()
        + getSavedAnswers()
        + guessLetter()
        + guessWord()
        + resetLettersGuessed()
    }
  }
  

  namespace DetectiveHangman {
    class DetectiveHangman.Game {
        {static} + addLimb()
        {static} + displayMysteryComponent()
        {static} + getRoundComponent()
        {static} + main()
        {static} + playGame()
        {static} + solveMystery()
    }
  }
  

  namespace DetectiveHangman {
    class DetectiveHangman.HangMan {
        - HangMan : String
        + HangMan()
        + addBody()
        + addHead()
        + addLeftArm()
        + addLeftLeg()
        + addRightArm()
        + addRightLeg()
        + displayStand()
        + getHangMan()
    }
  }
  

  namespace DetectiveHangman {
    class DetectiveHangman.Riddle {
        - answer : String
        - currentBlanks : String
        - fullRiddle : String
        - isSolved : boolean
        - maskedRiddle : String
        - missingWord : String
        + Riddle()
        + Riddle()
        + displayBlanks()
        + getFullRiddle()
        + getMaskedRiddle()
        + getMissingWord()
        + getSolved()
        + isSolved()
        + setSolved()
        + updateBlanks()
        - generateMaskedRiddle()
    }
  }
  

  namespace DetectiveHangman {
    enum RiddleComponent {
      LOCATION
      MOTIVE
      MURDERER
      VICTIM
      WEAPON
    }
  }
  

  namespace DetectiveHangman {
    class DetectiveHangman.RiddleManager {
        - locationRiddles : File
        - motiveRiddles : File
        - murdererRiddles : File
        - victimRiddles : File
        - weaponRiddles : File
        + RiddleManager()
        + getRandomRiddleForComponent()
        + openFile()
    }
  }
  

  namespace DetectiveHangman {
    class DetectiveHangman.Scene {
        - finalScene : String
        + Scene()
        + getFinalScene()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
